[project]
name = "ffmpeg-videoprocessing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyqt6>=6.9.1",
    "pysrt>=1.1.2",
]
